# Generated by Django 4.2.1 on 2023-06-16 00:46

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_medico', models.CharField(max_length=255)),
                ('especialidad', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(max_length=255)),
                ('apellido_paciente', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMedicamento',
            fields=[
                ('id_tipo_medicamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_medicamento', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_usuario', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='cantidad_medicamento',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='fecha_elab_medicamento',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='fecha_venc_medicamento',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='id',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='descripcion',
            field=models.CharField(default='Descripción por defecto', max_length=255),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='id_medicamento',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nombre_medicamento',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='id_tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario'),
        ),
        migrations.CreateModel(
            name='Farmaceutico',
            fields=[
                ('id_farmaceutico', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_farmaceutico', models.CharField(max_length=255)),
                ('apellido_farmaceutico', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('id_tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id_entrega', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
                ('id_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id_detalle_receta', models.IntegerField(primary_key=True, serialize=False)),
                ('dosis', models.CharField(max_length=255)),
                ('frecuencia', models.CharField(max_length=255)),
                ('id_medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.medicamento')),
                ('id_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEntrega',
            fields=[
                ('id_detalle_entrega', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_entregada', models.IntegerField()),
                ('id_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entrega')),
                ('id_medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(related_name='custom_users', to='auth.group')),
                ('id_tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario')),
                ('user_permissions', models.ManyToManyField(related_name='custom_users', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='medicamento',
            name='id_tipo_medicamento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.tipomedicamento'),
        ),
    ]
